# general configuration
url: 
baseurl: ''

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/logo.jpg"
  # author will appear under the avatar (optional)
  author: "The Eye"
  # tagline will appear under the title (optional)
  tagline: "A blog describing our adventures"
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: false

# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: true
